baseurl: 'https://www.revaw.art'
languageCode: en-us
title: Reva W Art
theme: hugo-identity-theme  
googleAnalytics: $GOOGLE_ANALYTICS_MEASUREMENT_ID
disableKinds:
  - page
  - section
  - taxonomy
  - taxonomyTerm
  - RSS
  - sitemap
  - robotsTXT
  - '404'
params:
  favicon_ico: favicon.ico
  favicon_ico_sizes: 16x16 32x32
  appleicon: apple.png
  personal:
    name: Reva W
    avatar: revaw.png
    position: Creator
    livesIn: '[United States](https://en.wikipedia.org/wiki/United_States)'
    scope:
      - 'Major key, don’t fall for the trap, stay focused'
      - 'Surround yourself with angels'
      - 'Bless up!'
    biography: >-
      . Cloth talk. Find peace, life is like a water fall, you’ve gotta flow. 
      How’s business? Boomin. Let me be clear, you have to make it through the 
      jungle to make it to paradise, that’s the key, Lion!
  contact:
    email: revaw@revaw.art
    enable: true
    title: Let's get in touch!
    namePlaceholder: Your name
    emailPlaceholder: Your e-mail
    messagePlaceholder: Your message
    buttonText: Send it
    success: Thank you for contacting me!
    error: 'Message could not be send. Please contact us at revaw@revaw.art'
  social:
    - title: Twitter
      icon: fa-twitter
      link: '#'
      target: _blank
    - title: Instagram
      icon: fa-instagram
      link: '#'
      target: _blank
    - title: Facebook
      icon: fa-facebook
      link: '#'
      target: _blank
  footer:
    copyright: Reva W

